#!/bin/sh

#make sure we get fresh keys
if [ ! -f /root/.regenerated_ssh_keys ]
then
	rm -rf /etc/ssh/ssh_host_rsa_key /etc/ssh/ssh_host_dsa_key

	ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa
	ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa
	ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -N '' -t ecdsa -b 521
fi

if ps -ef | grep -q sshd
then
	killall sshd
fi

/usr/sbin/sshd -D &
